### ISSUE TITLE
Textstat installation issue Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by repunzel123** [shivam5992/textstat#84]
I download the textstat-0.5.4.tar.gz from PYpi website and put it under the C:\Users\Liuruohan\.spyder-py3>, I try to install it on cmd, I get an error,

```
C:\Users\Liuruohan\.spyder-py3>pip install textstat
Collecting textstat
  Using cached https://files.pythonhosted.org/packages/9b/78/a050fa0f13c04db10c891167204e2cd0c0ae1be40842a10eaf5348360f94/textstat-0.5.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\LIURUO~1\AppData\Local\Temp\pip-install-f9zkkizd\textstat\setup.py", line 11, in <module>
        long_description=open('README.md').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 6704: illegal multibyte sequence
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\LIURUO~1\AppData\Local\Temp\pip-install-f9zkkizd\textstat\
```

I am sure my setup tools are upgraded, and I also tried conda install textstat in anaconda cmd, I also tried to extract textstat file first and move it under the spyder file, but still this problem still exists
It seems a number of people are struggled in this issues, but I could not found the answer. Can anyone help me?

**Comment by alxwrd** [comment]
@repunzel123 I've just pushed version [`0.5.5`](https://pypi.org/project/textstat/0.5.5/) to pypi.

This should hopefully address the problem you are having with the installation.

Could you please try and install this? Let me know if there are any issues.

**Comment by repunzel123** [comment]
Hi, thank you for help.
Textstat is successfully installed, thanks, but when I try to calculate gunning fog index by using the examples on pypi, the error still exists: AttributeError: module 'textstat' has no attribute 'gunning_fog'

**Comment by alxwrd** [comment]
@repunzel123 Have you removed the files you manually copied over? I think somehow you're importing the `textstat.py` file, instead of importing the module.

**Comment by repunzel123** [comment]
Hi, thank you for your help. Problem solved. I did install the package, but I do not why the effective package was belong to the file of python rather than spyder. I changed the path and then it is fine. Thank you for your time
